name: CI/CD
on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  DOCKER_IMAGE_NAME: celconeto
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  checkout-install-build:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run install and build
        run: |
          npm install
          npm run build

  build-and-push:
    needs: checkout-install-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: celconeto
          password: Ccr#2k222

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Docker.io
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: celconeto/first-deploy-github-actions:1.0.5

  publish-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        run: |
          [ $(uname -m) = x86_64 ]
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          [ $(uname -m) = aarch64 ] 
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Check instalation kubectl
        run: kubectl get pods
