name: CI/CD
on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  DOCKER_IMAGE_NAME: celconeto
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  deploy:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run install and build
        run: |
          npm install
          npm run build

  build-and-push:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: celconeto
          password: Ccr#2k222

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Docker.io
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: celconeto/first-deploy-github-actions:1.0.5

  publish-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: |
          kubectl apply -f infra/my-app-deployment.yaml
